url: http://drewfrom.space/
baseurl:

# Site settings
title: Drew Price
title_tag: Drew Price | Webz
email: drew.s.price@gmail.com
description: "I build things for the interwebz."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: A0866E
  secondary: DAD1C5
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Drew Price
  pic: 1
  position: Web Developer
  social:
    - title: twitter
      url: https://twitter.com/drewfromspace
    - title: linkedin
      url: https://www.linkedin.com/in/drewscottprice
    - title: github
      url: http://github.com/drewprice

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/drewfromspace
  - title: facebook
    url: https://www.facebook.com/drewscottprice
  - title: stack-overflow
    url: http://stackoverflow.com/users/3940242/drew-price
  - title: linkedin
    url: https://www.linkedin.com/in/drewscottprice
  - title: github
    url: http://github.com/drewprice

# Postal address (add as many lines as necessary)
address:
  - line:
  - line:
  - line:
  - line:

# Build settings
markdown: kramdown
permalink: pretty
